# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('os', models.CharField(max_length=30, verbose_name='操作系统')),
                ('ip', models.CharField(max_length=15, verbose_name='IP')),
                ('brand', models.CharField(max_length=30, verbose_name='品牌')),
                ('serial_num', models.CharField(max_length=30, verbose_name='S/N码')),
                ('discription', models.CharField(max_length=50, verbose_name='描述信息')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '电脑',
                'verbose_name_plural': '电脑',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('ip', models.CharField(max_length=15, verbose_name='IP')),
                ('discription', models.CharField(max_length=50, verbose_name='描述信息')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '打印机',
                'verbose_name_plural': '打印机',
            },
        ),
        migrations.CreateModel(
            name='RepairInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('discription', models.TextField(help_text='请输入内容', verbose_name='描述')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '维修记录',
                'verbose_name_plural': '维修记录',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='工位名称')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='工位创建时间')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineinfor.Computer', verbose_name='主机')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineinfor.Printer', verbose_name='打印机')),
                ('repairinfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineinfor.RepairInfor', verbose_name='维修信息')),
            ],
            options={
                'verbose_name': '工位',
                'verbose_name_plural': '工位',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='车间名称')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '车间',
                'verbose_name_plural': '车间',
            },
        ),
        migrations.AddField(
            model_name='station',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineinfor.Workshop', verbose_name='所属车间'),
        ),
    ]
